[project]
name = "ananta"
version = "0.1.0"
description = "AI Agent Framework"
dependencies = [
    "flask",
    "requests",
    "flask-cors",
    "pydantic",
    "pydantic-settings",
    "python-dotenv",
    "prometheus-client",
    "pyjwt",
    "portalocker",
    "flasgger",
    "psutil",
    "sqlmodel",
    "psycopg2-binary",
    "pyotp",
    "qrcode",
    "cryptography",
    "alembic",
    "typer",
    "shell_gpt",
    "prompt_toolkit",
    "click",
    "redis",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "httpx",
    "flake8",
    "mypy"
]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "psycopg2.*",
    "flask_cors.*",
    "prometheus_client.*"
]
ignore_missing_imports = true
